"""
Unified public API for the registers package.

This module re-exports convenience symbols while preserving legacy submodule
imports such as ``import registers.cron.daemon``.
"""

from registers import cli as cli
from registers import cron as cron
from registers import db as db
from registers.cli import (
    DIContainer,
    Dispatcher,
    MiddlewareChain,
    MISSING,
    ArgumentEntry,
    CommandEntry,
    CommandExecutionError,
    CommandRegistry,
    DependencyNotFoundError,
    DuplicateCommandError,
    ParseError,
    PluginLoadError,
    RegistrationError,
    UnknownCommandError,
    alias,
    argument,
    get_registry,
    list_commands,
    load_plugins,
    logging_middleware_post,
    logging_middleware_pre,
    option,
    parse_command_args,
    register,
    reset_registry,
    run,
    run_shell,
)
from registers.core.contracts import (
    RegistryAccessorContract,
    RegistryCollectionContract,
    RegistryLifecycleContract,
)
from registers.core.errors import RegistrationErrorBase
from registers.core.logging import log_exception
from registers.cron import (
    CronAdapterError,
    CronError,
    CronLookupError,
    CronRegistrationError,
    CronRegistry,
    CronRuntimeError,
    CronTriggerError,
    CronWorkspaceError,
    CronWorkspaceRuntimeError,
    JobEntry,
    TriggerSpec,
    cron as cron_schedule,
    ensure_workspace,
    event,
    get_registry as cron_get_registry,
    install_cli,
    interval,
    job,
    list_workflows,
    register as cron_register,
    register_workflow,
    reset_registry as cron_reset_registry,
    run as cron_run,
    run_daemon,
    run_registered_workflow,
    start,
    sync_project_jobs,
    use_registry,
    watch,
)
from registers.db import (
    BelongsTo,
    ConfigurationError,
    DatabaseRegistry,
    DuplicateKeyError,
    HasMany,
    HasManyThrough,
    ImmutableFieldError,
    InvalidPrimaryKeyAssignmentError,
    InvalidQueryError,
    MigrationError,
    ModelRegistrationError,
    RecordNotFoundError,
    RegistryConfig,
    RegistryError,
    RelationshipError,
    SchemaError,
    SchemaManager,
    UniqueConstraintError,
    database_registry,
    db_field,
    dispose_all,
    dispose_engine,
    get_engine,
    hash_password,
    is_password_hash,
    verify_password,
)

__all__ = [
    "cli",
    "cron",
    "db",
    "register",
    "argument",
    "option",
    "alias",
    "run",
    "run_shell",
    "list_commands",
    "get_registry",
    "reset_registry",
    "CommandRegistry",
    "CommandEntry",
    "ArgumentEntry",
    "MISSING",
    "parse_command_args",
    "ParseError",
    "DIContainer",
    "Dispatcher",
    "MiddlewareChain",
    "load_plugins",
    "logging_middleware_pre",
    "logging_middleware_post",
    "CommandExecutionError",
    "DependencyNotFoundError",
    "DuplicateCommandError",
    "RegistrationError",
    "PluginLoadError",
    "UnknownCommandError",
    "RegistrationErrorBase",
    "log_exception",
    "RegistryAccessorContract",
    "RegistryCollectionContract",
    "RegistryLifecycleContract",
    "job",
    "watch",
    "interval",
    "event",
    "start",
    "install_cli",
    "use_registry",
    "sync_project_jobs",
    "run_daemon",
    "ensure_workspace",
    "register_workflow",
    "list_workflows",
    "run_registered_workflow",
    "CronRegistry",
    "JobEntry",
    "TriggerSpec",
    "CronError",
    "CronRegistrationError",
    "CronTriggerError",
    "CronLookupError",
    "CronRuntimeError",
    "CronWorkspaceError",
    "CronWorkspaceRuntimeError",
    "CronAdapterError",
    "cron_schedule",
    "cron_register",
    "cron_run",
    "cron_get_registry",
    "cron_reset_registry",
    "database_registry",
    "DatabaseRegistry",
    "db_field",
    "hash_password",
    "is_password_hash",
    "verify_password",
    "HasMany",
    "BelongsTo",
    "HasManyThrough",
    "SchemaManager",
    "get_engine",
    "dispose_engine",
    "dispose_all",
    "RegistryConfig",
    "RegistryError",
    "ConfigurationError",
    "ModelRegistrationError",
    "SchemaError",
    "MigrationError",
    "RelationshipError",
    "DuplicateKeyError",
    "InvalidPrimaryKeyAssignmentError",
    "ImmutableFieldError",
    "UniqueConstraintError",
    "RecordNotFoundError",
    "InvalidQueryError",
]
